function [fitresult, gof] = createFit(X3, Y3, H3)
%CREATEFIT(X3,Y3,H3)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : X3
%      Y Input : Y3
%      Z Output: H3
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Nov-2019 15:48:41


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( X3, Y3, H3 );

% Set up fittype and options.
ft = fittype( 'loess' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

% Create a figure for the plots.
figure( 'Name', 'untitled fit 1' );

% Plot fit with data.
subplot( 2, 1, 1 );
plot( fitresult, [xData, yData], zData );
% Label axes
xlabel( 'X3', 'Interpreter', 'none' );
ylabel( 'Y3', 'Interpreter', 'none' );
zlabel( 'H3', 'Interpreter', 'none' );
grid on
view( -48.1, -4.5 );

% Make contour plot.
subplot( 2, 1, 2 );
plot( fitresult, [xData, yData], zData, 'Style', 'Contour' );
% Label axes
xlabel( 'X3', 'Interpreter', 'none' );
ylabel( 'Y3', 'Interpreter', 'none' );
grid on


